spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    contextPath: /v1
athena:
  region: us-east-1
  workgroup: primary
  catalog: AwsDataCatalog
  database: tickit_demo
  limit: 25
  client-execution-timeout: 100000
  retry-sleep: 1000
  results-bucket: ${RESULTS_BUCKET}
  named-query-id: ${NAMED_QUERY_ID}
---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 60000 # 1000 ms * 60 * 1 = 1 min
      enable-statistics: true
server:
  port: 8080
logging:
  level:
    root: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
---
spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: ${REDIS_HOST}
    port: 6379
  cache:
    redis:
      time-to-live: 300000 # 1000 ms * 60 * 5 = 5 min
      enable-statistics: true
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
    jmx:
      exposure:
        include: health