global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: 'spring-boot-docker'
    metrics_path: '/v1/actuator/prometheus'
    static_configs:
      - targets: ['athena-spring-app:8080']